# Generated by Django 4.2.1 on 2023-06-23 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=50, verbose_name='Raza')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'raza',
                'verbose_name_plural': 'razas',
                'ordering': ['breed'],
            },
        ),
        migrations.CreateModel(
            name='MascotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascotType', models.CharField(max_length=50, verbose_name='Tipo de mascota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.breed', verbose_name='Raza')),
            ],
            options={
                'verbose_name': 'tipo de mascota',
                'verbose_name_plural': 'tipo de mascotas',
                'ordering': ['mascotType', 'breed'],
            },
        ),
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('idMascot', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='videojuegos', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.breed', verbose_name='Raza')),
                ('mascotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.mascottype', verbose_name='Tipo de mascota')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['name', 'mascotType', 'breed'],
            },
        ),
    ]
