# Generated by Django 4.2.1 on 2023-06-24 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['breed'], 'verbose_name': 'raza de mascota', 'verbose_name_plural': 'raza de mascotas'},
        ),
        migrations.AlterModelOptions(
            name='mascottype',
            options={'ordering': ['mascotType'], 'verbose_name': 'tipo de mascota', 'verbose_name_plural': 'tipo de mascotas'},
        ),
        migrations.RemoveField(
            model_name='mascottype',
            name='breed',
        ),
        migrations.AlterField(
            model_name='breed',
            name='breed',
            field=models.CharField(max_length=50, verbose_name='Raza de mascota'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.breed', verbose_name='Raza de mascota'),
        ),
        migrations.AlterField(
            model_name='mascot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mascotas', verbose_name='Imagen'),
        ),
    ]
