# Generated by Django 4.2.1 on 2023-06-26 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_breed_options_alter_mascottype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascot',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='mascot',
            name='mascotType',
        ),
        migrations.DeleteModel(
            name='Breed',
        ),
        migrations.DeleteModel(
            name='Mascot',
        ),
        migrations.DeleteModel(
            name='MascotType',
        ),
    ]
