# Generated by Django 4.2.1 on 2023-06-26 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crud', '0003_remove_mascot_breed_remove_mascot_mascottype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MascotType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mascotType', models.CharField(max_length=20, verbose_name='Tipo de mascota')),
                ('breed', models.CharField(max_length=40, verbose_name='Raza de mascota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'tipo de mascota',
                'verbose_name_plural': 'tipo de mascota',
                'ordering': ['mascotType'],
            },
        ),
        migrations.CreateModel(
            name='Mascot',
            fields=[
                ('idMascot', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='mascotas', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raza', to='crud.mascottype', verbose_name='Raza de Mascota')),
                ('mascotType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo', to='crud.mascottype', verbose_name='Tipo de Mascota')),
            ],
            options={
                'verbose_name': 'mascota',
                'verbose_name_plural': 'mascotas',
                'ordering': ['name', 'mascotType'],
            },
        ),
    ]
