# Generated by Django 4.2.1 on 2023-06-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_remove_mascottype_breed_alter_mascot_breed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vaccine',
            options={'ordering': ['id'], 'verbose_name': 'vacuna', 'verbose_name_plural': 'vacunas'},
        ),
    ]
