# Generated by Django 4.2.1 on 2023-06-27 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_vaccine_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='Genero de mascota')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualización')),
            ],
            options={
                'verbose_name': 'genero',
                'verbose_name_plural': 'generos',
                'ordering': ['gender'],
            },
        ),
        migrations.AlterModelOptions(
            name='mascottype',
            options={'ordering': ['mascotType'], 'verbose_name': 'tipo de mascota', 'verbose_name_plural': 'tipo de mascotas'},
        ),
        migrations.RemoveField(
            model_name='mascot',
            name='vaccine',
        ),
        migrations.AlterField(
            model_name='mascot',
            name='mascotType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.mascottype', verbose_name='Tipo de Mascota'),
        ),
        migrations.DeleteModel(
            name='Vaccine',
        ),
        migrations.AddField(
            model_name='mascot',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.gender', verbose_name='Genero de Mascota'),
        ),
    ]
